# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\",\n\x16GetProjectTasksRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x05\"4\n\x17GetProjectTasksResponse\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.task.Task\"D\n\x1dGetTasksForUserProjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\";\n\x1eGetTasksForUserProjectResponse\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.task.Task\"\x82\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\x12\x0f\n\x07user_Id\x18\x05 \x01(\x05\x12\x17\n\nproject_id\x18\x06 \x01(\x05H\x00\x88\x01\x01\x42\r\n\x0b_project_id2\xc5\x01\n\x0bTaskService\x12Q\n\x12GetTasksForProject\x12\x1c.task.GetProjectTasksRequest\x1a\x1d.task.GetProjectTasksResponse\x12\x63\n\x16GetTasksForUserProject\x12#.task.GetTasksForUserProjectRequest\x1a$.task.GetTasksForUserProjectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPROJECTTASKSREQUEST']._serialized_start=20
  _globals['_GETPROJECTTASKSREQUEST']._serialized_end=64
  _globals['_GETPROJECTTASKSRESPONSE']._serialized_start=66
  _globals['_GETPROJECTTASKSRESPONSE']._serialized_end=118
  _globals['_GETTASKSFORUSERPROJECTREQUEST']._serialized_start=120
  _globals['_GETTASKSFORUSERPROJECTREQUEST']._serialized_end=188
  _globals['_GETTASKSFORUSERPROJECTRESPONSE']._serialized_start=190
  _globals['_GETTASKSFORUSERPROJECTRESPONSE']._serialized_end=249
  _globals['_TASK']._serialized_start=252
  _globals['_TASK']._serialized_end=382
  _globals['_TASKSERVICE']._serialized_start=385
  _globals['_TASKSERVICE']._serialized_end=582
# @@protoc_insertion_point(module_scope)
