syntax = "proto3";

package task;

service TaskService {
    rpc GetTasksForProject (GetProjectTasksRequest) returns (GetProjectTasksResponse);
    rpc GetTasksForUserProject (GetTasksForUserProjectRequest) returns (GetTasksForUserProjectResponse);
}

message GetProjectTasksRequest {
    int32 project_id = 1;
}

message GetProjectTasksResponse {
    repeated Task tasks = 1;
}

message GetTasksForUserProjectRequest {
    int32 user_id = 1;
    int32 project_id = 2;
}

message GetTasksForUserProjectResponse {
    repeated Task tasks = 1;
}

message Task {
    int32 id = 1;
    string title = 2;
    string description = 3;
    bool completed = 4; // e.g., "TODO", "IN_PROGRESS", "DONE"
    int32 user_Id = 5; // user_id of the assignee
    optional int32 project_id = 6; // project_id to which the task belongs
}